### ISSUE TITLE
Unknown record type.

### ISSUE THREAD

**Issue by beatsforthemind** [scriptotek/simplemarcparser#5]
I am trying to parse the output of the Zebra SRU included with Koha. This is probably not an issue with your code, more likely with the data itself. When building the query I noticed that Zebra will not recognize `'recordSchema' => 'marcxchange'` so I have to use `'recordSchema' => 'marcxml'`. Is this creating the problem? Zebra will also only return version 1.1 formatting, not sure if that makes any difference.

This is the error I am receiving:
`mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Scriptotek\\SimpleMarcParser\\ParserException' with message 'Unknown record type.`

Here is the marcxml up to the leader:
```
<zs:searchRetrieveResponse xmlns:zs="http://www.loc.gov/zing/srw/">
<zs:version>1.1</zs:version>
<zs:numberOfRecords>1</zs:numberOfRecords>
<zs:records>
<zs:record>
<zs:recordSchema>marcxml</zs:recordSchema>
<zs:recordPacking>xml</zs:recordPacking>
<zs:recordData>
<record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.loc.gov/MARC21/slim" xsi:schemaLocation="http://www.loc.gov/MARC21/slim http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd">
<leader>nam a22 Ia 4500</leader>
```

Any help would be great!

**Comment by danmichaelo** [comment]
`'recordSchema' => 'marcxml'.` is fine (and actually more common :)). And 1.1 should be fine too.

But there's something fishy with the leader.. It should always be 24 characters long, see https://www.loc.gov/marc/bibliographic/bdleader.html .

Here's an example of a valid leader: https://github.com/scriptotek/simplemarcparser/blob/master/tests/ParserTest.php#L31

I'm using position 6 to determine record type:

https://github.com/scriptotek/simplemarcparser/blob/master/src/Parser.php#L32-L59

You could give https://github.com/scriptotek/php-marc a try, I'm not sure if it's less strict on this or not.

**Comment by danmichaelo** [comment]
Closing per https://twitter.com/beatsforthemind/status/720292665992945664
